### ISSUE TITLE
Add team summary information

### ISSUE THREAD

**Issue by mukrop** [zverinec/interlos-web#14]
Add stats for the number of team members in individual categories to https://interlos.fi.muni.cz/archive/teams-year2016.

**Comment by repli2dev** [comment]
After time passed I cannot see what was the matter? Add number of team members after team name?

**Comment by mukrop** [comment]
For political (and curiosity) reasons, we need the number of player for inter-year comparison. E.g. modify the header "Středoškoláci" to "Středoškoláci (256 hráčů v 76 týmech)".

**Comment by repli2dev** [comment]
Done.
