### ISSUE TITLE
Fully migrate to zverinec

### ISSUE THREAD

**Issue by mukrop** [zverinec/interlos-web#2]
Migrate issues and server repo origin.
Especially with the new server admin in mind.

**Comment by repli2dev** [comment]
Issues migrated. What do you mean by "server repo origin"?

**Comment by mukrop** [comment]
I mean that if I log into the live system, interlos-devel system and such, the default tracking branch for git pull will be the correct one (which I believe to be zverinec GitHub, hm?).
The request arose because 'git push' on my local machine pushed to yavanna, which slightly surprised me.
If both the live system and interlos-devel are correctly set, feel free to close the issue.

**Comment by repli2dev** [comment]
Both instances (devel, production) on production server have now only one remote (zverinec). Therefore I close this issue.
