### ISSUE TITLE
Avoid robots registration

### ISSUE THREAD

**Issue by malinajan** [zverinec/interlos-web#28]
In 2021-spring event cca 2 robots per day were registered. Some robots seem to pass through current reCAPTCHA protection. Registration of robots should be avoided.

**Comment by repli2dev** [comment]
@horacekj please verify if https://www.google.com/recaptcha/admin/site/343419448 project on production is used.

I do not know any better way than ReCaptcha when failing... I would rather suppose not validating it possible than that the bots get pass it.

Investigation ETA: 1 hour

**Comment by malinajan** [comment]
Aha, interesting. Everything seems to work, I'll try to increase "difficulty" of reCAPTCHA as a reaction to future incidents.
