### ISSUE TITLE
Graphics tweaks

### ISSUE THREAD

**Issue by repli2dev** [zverinec/interlos-web#3]
- logolink OP VK aliased to brown instead of white
- VPS free logo in dark brown instead of black

**Comment by mukrop** [comment]
OPVK logo-link is irrelevant, new (brown-adjusted) VPSfree logo in attachment.
![vpsfree](https://user-images.githubusercontent.com/1871676/47880072-8cf63480-de22-11e8-8b76-81a28090e18b.png)
