### ISSUE TITLE
Upgrade to Nette 3.0 and PHP 7.4

### ISSUE THREAD

**Issue by repli2dev** [zverinec/interlos-web#30]
As time flies the PHP 7.1 is greatly outdated and should be switched to PHP 7.4, which brings the need with upgrade (rewrite) to Nette 3.0.

This won't be a piece cake, but it won't be scary also (around 8-16 hours) and will need to retest it (when developing) and probably to run full-featured test of the game... So probably better to do it in the next season.

**Comment by malinajan** [comment]
Done.
