### ISSUE TITLE
Řazení týmů

### ISSUE THREAD

**Issue by verandabe** [zverinec/interlos-web#31]
Řadit týmy v seznamu týmů podle ID.

**Comment by repli2dev** [comment]
Je ID lepší než po kategoriích a abecedně?

**Comment by verandabe** [comment]
Po kategoriích bych nechala, abecedně případně může taky být místo ID, ale aktuálně se to řadí náhodně a mění se to po refreshi.

**Comment by malinajan** [comment]
Verča říkala, že preferuje ID - asi aby šly snadno vidět nové týmy. Mě osobně neuráží ani abecední řazení. Na druhou stranu, tým vyhledáš pomocí Ctrl+F, informace o pořadí registrace se také hodí. Nebál bych se řazení podle id.

**Comment by repli2dev** [comment]
TMOU třeba používá abecední řazení... Ještě je potřeba vzít v potaz očekávání uživatelů a byť my jako informaticky prakticky tu stránku používáme jen s najít a nahradit, mohu vám garantovat, že velká část uživatelů pojede podle abecedy (tzn. spíš skočí klávesou/scrollbarem nakonec) než aby použila hledání.

Tzn. pokud chcete ID, tak to nahoře tučně napište (což ale většina lidí stejně mine, ale aspoň nebude mít právo se rozčilovat), protože bez toho je to pro všechny co na tu stránku příjdou jen "náhodné řazení".

Btw. za tohle pravděpodobně může databáze, v nějaké verzi MySQL/MariaDB přestaly být jisté dotazy stabilní z hlediska vráceného pořadí.

**Comment by malinajan** [comment]
Dobře, může být klidně abecedně. Osobně nemám striktní preferenci.
