### ISSUE TITLE
Expirující session

### ISSUE THREAD

**Issue by malinajan** [zverinec/interlos-web#35]
Tým píše: "Když už tam musí být ta @#$%&!!! CAPTCHA, nemůže aspoň session vydržet šest hodin, aby se člověk pře hrou přihlásil a zůstal přihlášený? Musel jsem se znovu přihlašovat prakticky při každé interakci se systémem – a měli to tak i ostatní v týmu."

Navrhuji zrušit reCAPTCHu na přihlášení. Nechat jen na registraci a reset hesla. A prodloužit platnost session.

**Comment by repli2dev** [comment]
Problem muze byt i systemu, tusim Debian mazacal session storage dir driv nez ty session vubec vyprsely...

**Comment by GalactusCZ** [comment]
Na tomto problému jsem provedl více testů a došel k závěru, že problém byl pravděpodobně v nastavení php.ini na serveru (session.gc_maxlifetime). V tomto nastavení bylo určeno smazání session na 24 minut. Důvodem nekonzistentnosti mezi uživateli byl pak fakt. že při znovunačtení webu (ač úmyslném nebo při interagování s nějakými prvky) se životnost session obnoví. Jak původní problém, tak jeho vyřešení jsem otestoval tak, že jsem se k webu přihlásil v prohlížečích Firefox a Brave a nechal je takto stát po nějaký čas. Při posledních testech mi pak přihlášení vydrželo přes 3 hodiny. Životnost byla kdyžtak změněna na celkem 4 hodiny.

**Comment by repli2dev** [comment]
No tohle je klasika... Ubuntu a debian mají v základu čištění, které čistí podle nastavení v konfigu, které je krátké, nebo přímo po určitém intervalu natvrdo.

**Comment by malinajan** [comment]
Vyřešeno.
